databases:
  - name: amcom_project
    databaseName: amcom_project
    user: admin

services:
  - type: web
    name: amcom_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn amcom_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amcom_project
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4