# Generated by Django 4.2.6 on 2023-11-03 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_code", models.CharField(max_length=50)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sale"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sale",
            name="products",
            field=models.ManyToManyField(through="core.SaleProduct", to="core.product"),
        ),
        migrations.AddField(
            model_name="sale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.seller"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "sale"), name="once_per_sale_product"
            ),
        ),
    ]
