# Generated by Django 4.2.6 on 2023-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_customer_email_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commissionpercentagebyweekday",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="commissionpercentagebyweekday",
            name="weekday",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                unique=True,
            ),
        ),
    ]
