# Generated by Django 4.2.6 on 2023-11-10 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_customer_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-date", "invoice_code"]},
        ),
    ]
